manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: m165437 # For nice-view-gem
      url-base: https://github.com/M165437 # For nice-view-gem
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem # For nice-view-gem
      remote: m165437 # For nice-view-gem
      revision: main # For nice-view-gem
  self:
    path: config
